# environment-ci.yml: Additional dependencies to install in the CI environment.
channels:
- conda-forge
- nodefaults
dependencies:
- make
- mypy
- myst-parser
- pre-commit
- pip
- pydata-sphinx-theme
- pytest
- pytest-cov
- sphinx
- sphinx-autoapi
- types-requests
- pip:
  - responses
